<?php
require_once "Vehicle.php";

class Tram extends Vehicle
{
    protected $arriage_count;
    protected $rail_type;

    /**
     * Tram constructor.
     * @param $arriage_count
     * @param $rail_type
     */
    public function __construct($passanger_count, $speed, $color,$arriage_count, $rail_type)
    {
        parent::__construct($passanger_count, $speed, $color);
        $this->arriage_count = $arriage_count;
        $this->rail_type = $rail_type;
    }

    public function toString()
    {
//        parent::toString(); // TODO: Change the autogenerated stub
        echo var_dump($this);
    }

    function stop()
    {
        echo 'tram stop on station ';
    }

    function Tstop()
    {
        echo 'tram stop on station ';
    }

    function next_gear()
    {
        echo 'tram next_gear ';
    }

    function previous_gear()
    {
        echo 'tram previous_gear ';
    }

    function profit_calculation()
    {
        echo 'tram profit_calculation 6.5 ';
    }

    function turn_left()
    {
        throw new Exception('Fatal error');
    }

    function turn_right()
    {
       throw new Exception('Fatal error');
    }


}